tests = exe{test_activation test_bit_identity test_detectors test_health test_input test_ledger test_output test_policy test_primitives test_react test_verify}

exe{test_activation}: c{test_activation} ../../src/liba{certifiable_monitor}
exe{test_bit_identity}: c{test_bit_identity} ../../src/liba{certifiable_monitor}
exe{test_detectors}: c{test_detectors} ../../src/liba{certifiable_monitor}
exe{test_health}: c{test_health} ../../src/liba{certifiable_monitor}
exe{test_input}: c{test_input} ../../src/liba{certifiable_monitor}
exe{test_ledger}: c{test_ledger} ../../src/liba{certifiable_monitor}
exe{test_output}: c{test_output} ../../src/liba{certifiable_monitor}
exe{test_policy}: c{test_policy} ../../src/liba{certifiable_monitor}
exe{test_primitives}: c{test_primitives} ../../src/liba{certifiable_monitor}
exe{test_react}: c{test_react} ../../src/liba{certifiable_monitor}
exe{test_verify}: c{test_verify} ../../src/liba{certifiable_monitor}

$tests:
{
  c.coptions += -UNDEBUG
  c.libs += -lm
  test = true
}

./: $tests
